### ISSUE TITLE
gerapy init failed complaining cannot import name 'version'

### ISSUE THREAD

**Issue by matifayaz** [Gerapy/Gerapy#2]
I've recently installed gerapy on a Python 3.6.3 virtual environment. After successful installation I executed:
`gerapy init`

and got this:
Traceback (most recent call last):
  File "/home/muhammad/development/virtualenvs/py3-pocs/bin/gerapy", line 7, in <module>
    from gerapy.cmd import cmd
  File "/home/muhammad/development/virtualenvs/py3-pocs/lib/python3.6/site-packages/gerapy/cmd/__init__.py", line 14, in <module>
    from gerapy import version
ImportError: cannot import name 'version'

**Comment by mtaziz** [comment]
@matifayaz, I had the same issue but I was able to run the application by doing the following:
under my site packages located in `~/projects/py36env/lib/python3.6/site-packages/gerapy`
There is `__init__.py` and it is empty which I updated as below. 
After, version import issue resolved. 
```
# __init__.py
__version__ = '0.7.0'
    def version():
        return __version__                     
```

**Comment by matifayaz** [comment]
Great!  Thank you Tariq. It's working now.

Do you have an idea on how can we convert the Chinese to English?

**Comment by Germey** [comment]
@mtaziz Thanks for your reply, I'm really appreciated.
@matifayaz I'm really sorry that I've removed the `version()` method from __init__.py because I tried to use 'VERSION' file to specify version.
Now I've fixed it and upgrade to 0.7.2
You can use upgrade or reinstall it.
I will release alpha, beta version first in the next versions  in case of ERROR.
Thanks for your issue~

**Comment by Germey** [comment]
@matifayaz Hey, I wonder where are you from. I'm Chinese from Beijing, China. 😁 If you feel any inconvenience I'm glad to convert it in the next version.

**Comment by matifayaz** [comment]
@Germey Thanks a lot for the prompt response and a quick action. I'll try after upgrading to the latest version.
I am from Pakistan :) What would be the quickest way to convert the application to English?

**Comment by mtaziz** [comment]
@matifayaz My pleasure:) 
@Germey , Thank you so much for your prompt headsup in fixing the version issue. 

Despite, the fact that I contacted you over Email on how to run the application , and you responded so promptly informing about howtos and I was able to run the application but since all the button's text in UI happens to be in Chinese, I could not be able to explore on every detail of the project , at least from front-end manipulation point of view. 
I very much like the Scrapy Spider Admin panel (Gerapy) and found worth trying. 

English Language Support: As you @Germey  mentioned, you would love to convert it in English. 
I can not thank you enough for being positive about the language conversion. I very much look forward to that. 

As a matter of fact, It would have been great addition and convenience for most of the users probably around the globe if we could run the `Gerapy` like in both language: English -> http://localhost:8000/en and Chinese - > http://localhost:8000/ch. Meaning `Gerapy` would reach global audience. 

I truly appreciate your effort and time in building such UI scrapy spider admin panel. 
Patiently looking forward to be in touch with you as dev work goes on and would love to contribute to it within myself. 

Thank you:)

**Comment by Germey** [comment]
@mtaziz @matifayaz  
Hi, English Support is finished and I'v upgrade Gerapy to 0.7.7, please upgrade it to use.
I've added Chinese/English Support, you can change the language by clicking the button in the top-right corner, and default language is English~
